# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 044765b2761a7196033b4b1689263b3acd71ac2b16bfe6daabf59f8f23292f28e713d2c1483e9d56cc14aec0d05d48c497e0fa0fa6e4550a09cff36f62d7dc54

test:
  secret_key_base: 38a6950f301337c6dc82a0fcb1c0bd680530d889185ff32039ff1ae3b1c151e6338080fe25e32745ff600f8b8611c54ed843a7991fdebae3d0f73e3db578f550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
